const GAME_ABI = [
	{
		inputs: [
			{ internalType: "string", name: "_channelId", type: "string" },
			{ internalType: "address", name: "_channelHost", type: "address" },
			{ internalType: "address", name: "_ticketsAddress", type: "address" },
			{ internalType: "address", name: "_treasury", type: "address" },
		],
		stateMutability: "nonpayable",
		type: "constructor",
	},
	{ inputs: [], name: "ECDSAInvalidSignature", type: "error" },
	{
		inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
		name: "ECDSAInvalidSignatureLength",
		type: "error",
	},
	{
		inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
		name: "ECDSAInvalidSignatureS",
		type: "error",
	},
	{ inputs: [], name: "GameNotActive", type: "error" },
	{ inputs: [], name: "GameNotOver", type: "error" },
	{ inputs: [], name: "InsufficientPayment", type: "error" },
	{ inputs: [], name: "InvalidParams", type: "error" },
	{ inputs: [], name: "InvalidSignature", type: "error" },
	{ inputs: [], name: "MaxSupply", type: "error" },
	{
		inputs: [{ internalType: "address", name: "owner", type: "address" }],
		name: "OwnableInvalidOwner",
		type: "error",
	},
	{
		inputs: [{ internalType: "address", name: "account", type: "address" }],
		name: "OwnableUnauthorizedAccount",
		type: "error",
	},
	{ inputs: [], name: "TransferFailed", type: "error" },
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: "uint256",
				name: "endTime",
				type: "uint256",
			},
		],
		name: "GameStarted",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "previousOwner",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "newOwner",
				type: "address",
			},
		],
		name: "OwnershipTransferred",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "buyer",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "castCreator",
				type: "address",
			},
			{
				indexed: true,
				internalType: "uint256",
				name: "senderFid",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "string",
				name: "castHash",
				type: "string",
			},
			{
				indexed: false,
				internalType: "address",
				name: "referrer",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "price",
				type: "uint256",
			},
		],
		name: "Purchased",
		type: "event",
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: "address",
				name: "seller",
				type: "address",
			},
			{
				indexed: true,
				internalType: "address",
				name: "castCreator",
				type: "address",
			},
			{
				indexed: true,
				internalType: "uint256",
				name: "senderFid",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "string",
				name: "castHash",
				type: "string",
			},
			{
				indexed: false,
				internalType: "address",
				name: "referrer",
				type: "address",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "amount",
				type: "uint256",
			},
			{
				indexed: false,
				internalType: "uint256",
				name: "price",
				type: "uint256",
			},
		],
		name: "Sold",
		type: "event",
	},
	{
		inputs: [
			{ internalType: "string", name: "castHash", type: "string" },
			{ internalType: "bytes", name: "data", type: "bytes" },
			{ internalType: "bytes", name: "signature", type: "bytes" },
		],
		name: "buy",
		outputs: [],
		stateMutability: "payable",
		type: "function",
	},
	{
		inputs: [],
		name: "channelHost",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "channelId",
		outputs: [{ internalType: "string", name: "", type: "string" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "creatorFeePercent",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "endTime",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "feePercent",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "isPaused",
		outputs: [{ internalType: "bool", name: "", type: "bool" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "string", name: "", type: "string" }],
		name: "nonce",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "owner",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address[]", name: "winners", type: "address[]" },
			{ internalType: "uint256[]", name: "amounts", type: "uint256[]" },
		],
		name: "payout",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "protocolTreasury",
		outputs: [{ internalType: "address", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "referralFeePercent",
		outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [],
		name: "renounceOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "castHash", type: "string" },
			{ internalType: "bytes", name: "data", type: "bytes" },
			{ internalType: "bytes", name: "signature", type: "bytes" },
		],
		name: "sell",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_endTime", type: "uint256" }],
		name: "startGame",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [],
		name: "tickets",
		outputs: [{ internalType: "contract Tickets", name: "", type: "address" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
		name: "transferOwnership",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_channelHost", type: "address" },
		],
		name: "updateChannelHost",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "bool", name: "_isPaused", type: "bool" }],
		name: "updateGameStatus",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_protocolTreasury", type: "address" },
		],
		name: "updateProtocolTreasury",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
];

export default GAME_ABI;
